name: Dependency Vulnerability Audit

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 0 */30 * 0"
  workflow_dispatch: {}

jobs:
  stats:
    runs-on: codeberg-small-lazy
    steps:
      - name: Checkout Code
        uses: https://code.forgejo.org/actions/checkout@v4

      - name: Run Audit
        uses: https://codeberg.org/nazara-project/actions/cargo-audit@cargo-audit-v0.22.0
