name: (Post Release) Amend manual release with binaries (Debian & MacOS)

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: codeberg-tiny-lazy
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            ext: tar.gz
          - os: macos-latest
            target: aarch64-apple-darwin
            ext: tar.gz
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            ext: zip

    steps:
      - uses: https://code.forgejo.org/actions/checkout@v4

      - name: Install Rust
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain stable
          source $HOME/.cargo/env

      - name: Build Project
        run: cargo build --release --target ${{ matrix.target }}

      - name: Package binary
        shell: bash
        run: |
          mkdir dist
          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            cp target/${{ matrix.target }}/release/thanix.exe dist/
            cd dist && zip ../thanix-${{ matrix.target }}.${{ matrix.ext }} thanix.exe
          else
            cp target/${{ matrix.target }}/release/thanix dist/
            cd dist && tar czf ../thanix-${{ matrix.target }}.${{ matrix.ext }} thanix
          fi

      - name: Build Debian Package
        if: matrix.os == 'ubuntu-latest'
        run: |
          cargo install cargo-deb --force
          cargo deb --output ../thanix-${{ matrix.target }}.deb

      - name: Upload to Release
        run: |
          for file in thanix-${{ matrix.target }}.${{ matrix.ext }} thanix-${{ matrix.target }}.deb; do
            if [ -f "$file" ]; then
              curl -X POST \
                -H "Authorization: token ${{ secrets.GIT_TOKEN }}" \
                -H "Content-Type: $(file -b --mime-type $file)" \
                --data-binary @"$file" \
                "${{ forgejo.event.release.upload_url }}"?name=$(basename "$file")
            fi
          done
