name: Style Checking

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  rustfmt:
    runs-on: codeberg-tiny-lazy

    steps:
      - name: Checkout Code
        uses: https://code.forgejo.org/actions/checkout@v4

      - name: Install Rust
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain stable

      - name: Run cargo fmt Check
        run: |
          source "$HOME/.cargo/env"
          cargo fmt -- --check

      - name: Run Clippy
        run: |
          source "$HOME/.cargo/env"
          cargo clippy
